### ISSUE TITLE
界面启动提示 404 错误

### ISSUE THREAD

**Issue by kerneltravel** [vito-go/fsearch_flutter#1]
错误信息：```
flutter: [INFO] 2023-09-09 14:56:48.449443 #2      homeInfo (package:fsearch_flutter/service/request.dart:16:5) DioException [bad response]: The request returned an invalid status code of 404. 
```

这个报错原因是什么？

图形客户端代码 是克隆到本地后未修改的，在android studio 环境里启动的。

软件版本：
flutter 3.13.3 ，dart 3.1.1

服务端 fsearch 的代码用的是example/example.go ， 端口 9097

**Comment by vito-go** [comment]
报错的原因是: 后端example中的启动端口非9097。

现已经修改并完善。请重新运行。
git clone --depth=1 https://github.com/vito-go/fsearch.git
cd fsearch && go run ./example/example.go

// expected outputs:
2023/09/11 10:09:11 server start: 9097
2023/09/11 10:09:11 fsearch: start detectFileSize ../testdata/log1.txt
2023/09/11 10:09:11 fsearch: start detectFileSize ../testdata/log2.txt
2023/09/11 10:09:11 unilog Client: ready to register ws: ws://127.0.0.1:9097/ws
2023/09/11 10:09:11 ready to accept a new client
2023/09/11 10:09:11 127.0.0.1:38918 register Scheme:lsh:, Check00:true,AppName:demoApp,HostName:10.236.148.250
2023/09/11 10:09:11 ready to send fiels: [log1.txt log2.txt]
2023/09/11 10:09:11 client regiter: appName: demoApp, NodeId:10001 HostName: 10.236.148.250 Files: [log1.txt log2.txt]

----

重启本flutter项目

**Comment by kerneltravel** [comment]
good，按照上述流程已经可以正常通过客户端 https://github.com/vito-go/fsearch_flutter 访问到 服务端 https://github.com/vito-go/fsearch 的日志搜索功能了。谢谢！
